// 文件内容由代码自动生成,请勿修改
module.exports = {
  "@awawa/import/consistent-type-specifier-style": ["warn", "prefer-top-level"],
  "@awawa/import/export": ["error"],
  "@awawa/import/extensions": ["warn", "never"],
  "@awawa/import/first": ["warn"],
  "@awawa/import/named": ["error"],
  "@awawa/import/newline-after-import": ["warn", { count: 1 }],
  "@awawa/import/no-absolute-path": ["error"],
  "@awawa/import/no-amd": ["error"],
  "@awawa/import/no-anonymous-default-export": [
    "warn",
    {
      allowArray: false,
      allowArrowFunction: false,
      allowAnonymousClass: false,
      allowAnonymousFunction: false,
      allowLiteral: false,
      allowObject: false,
    },
  ],
  "@awawa/import/no-commonjs": ["warn", { allowPrimitiveModules: true }],
  "@awawa/import/no-cycle": ["error", { maxDepth: "∞" }],
  "@awawa/import/no-duplicates": ["error"],
  "@awawa/import/no-dynamic-require": ["error"],
  "@awawa/import/no-extraneous-dependencies": [
    "warn",
    {
      devDependencies: [
        "test/**",
        "tests/**",
        "spec/**",
        "**/__tests__/**",
        "**/__mocks__/**",
        "*.test.{js,jsx,ts,tsx}",
        "**/*.test.{js,jsx,ts,tsx}",
        "**/*.test-*.{js,jsx,ts,tsx}",
        "**/*{.,_}{test,spec}.{js,jsx,ts,tsx}",
        "**/jest.config.js",
        "**/jest.setup.js",
        "**/vue.config.js",
        "**/webpack.config.js",
        "**/webpack.config.*.js",
        "**/rollup.config.js",
        "**/rollup.config.*.js",
        "**/gulpfile.js",
        "**/gulpfile.*.js",
        "**/Gruntfile{,.js}",
        "**/protractor.conf.js",
        "**/protractor.conf.*.js",
        "**/karma.conf.js",
        "**/.eslintrc.js",
      ],
      optionalDependencies: false,
    },
  ],
  "@awawa/import/no-import-module-exports": ["error", { exceptions: [] }],
  "@awawa/import/no-mutable-exports": ["warn"],
  "@awawa/import/no-named-as-default-member": ["warn"],
  "@awawa/import/no-named-as-default": ["error"],
  "@awawa/import/no-named-default": ["error"],
  "@awawa/import/no-relative-packages": ["error"],
  "@awawa/import/no-self-import": ["error"],
  "@awawa/import/no-unresolved": [
    "error",
    { commonjs: true, caseSensitive: true },
  ],
  "@awawa/import/no-useless-path-segments": ["error", { commonjs: true }],
  "@awawa/import/no-webpack-loader-syntax": ["error"],
  "@awawa/import/order": [
    "warn",
    {
      groups: [
        "builtin",
        "external",
        "internal",
        "parent",
        "sibling",
        "index",
        "type",
        "object",
      ],
      "newlines-between": "always",
      warnOnUnassignedImports: true,
      alphabetize: { order: "asc", caseInsensitive: true },
    },
  ],
  "@awawa/import/prefer-default-export": ["warn"],
};
