// 文件内容由代码自动生成,请勿修改
module.exports = {
  "@awawa/@typescript-eslint/adjacent-overload-signatures": ["error"],
  "@awawa/@typescript-eslint/ban-ts-comment": ["error"],
  "@awawa/@typescript-eslint/ban-types": ["error"],
  "@awawa/@typescript-eslint/no-array-constructor": ["error"],
  "@awawa/@typescript-eslint/no-empty-function": ["error"],
  "@awawa/@typescript-eslint/no-empty-interface": ["error"],
  "@awawa/@typescript-eslint/no-explicit-any": ["warn"],
  "@awawa/@typescript-eslint/no-extra-non-null-assertion": ["error"],
  "@awawa/@typescript-eslint/no-inferrable-types": ["error"],
  "@awawa/@typescript-eslint/no-loss-of-precision": ["error"],
  "@awawa/@typescript-eslint/no-misused-new": ["error"],
  "@awawa/@typescript-eslint/no-namespace": ["error"],
  "@awawa/@typescript-eslint/no-non-null-asserted-optional-chain": ["error"],
  "@awawa/@typescript-eslint/no-non-null-assertion": ["warn"],
  "@awawa/@typescript-eslint/no-shadow": ["error"],
  "@awawa/@typescript-eslint/no-this-alias": ["error"],
  "@awawa/@typescript-eslint/no-unnecessary-type-constraint": ["error"],
  "@awawa/@typescript-eslint/no-unused-vars": ["warn"],
  "@awawa/@typescript-eslint/no-var-requires": ["error"],
  "@awawa/@typescript-eslint/prefer-as-const": ["error"],
  "@awawa/@typescript-eslint/triple-slash-reference": ["error"],
};
