// 文件自动生成,请勿修改
module.exports = {
  "adjacent-overload-signatures": "必须将函数重载签名放在一起",
  "ban-ts-comment": "禁止使用`@ts-<directive>`注释",
  "ban-types": "禁止使用特定类型",
  "no-array-constructor": "禁止使用`Array`构造函数",
  "no-empty-function": "禁止空函数",
  "no-empty-interface": "禁止声明空接口",
  "no-explicit-any": "禁止使用`any`类型",
  "no-extra-non-null-assertion": "禁止多余的非空断言",
  "no-inferrable-types":
    "禁止对初始化为数字、字符串或布尔值的变量或参数进行显式类型声明",
  "no-loss-of-precision": "禁止使用会丢失精度的数字字面量",
  "no-misused-new": "禁止错误地定义`new`和`constructor`",
  "no-namespace": "禁止使用TypeScript命名空间",
  "no-non-null-asserted-optional-chain": "禁止在可选链表达式后使用非空断言",
  "no-non-null-assertion": "禁止使用非空断言操作符`!`",
  "no-shadow": "每个文件中只能有一个类",
  "no-this-alias": "禁止别名`this`",
  "no-unnecessary-type-constraint": "禁止不必要的类型约束",
  "no-unused-vars": "禁止未使用的变量",
  "no-var-requires": "禁止在import语句之外使用require",
  "prefer-as-const": "推荐使用`as const`而不是字面类型",
  "triple-slash-reference": "禁止使用三斜线指令",
};
