// 文件内容由代码自动生成,请勿修改
module.exports = {
  "vue/comment-directive": "off",
  "vue/jsx-uses-vars": "off",
  "vue/multi-word-component-names": "off",
  "vue/no-arrow-functions-in-watch": "off",
  "vue/no-async-in-computed-properties": "off",
  "vue/no-child-content": "off",
  "vue/no-computed-properties-in-data": "off",
  "vue/no-deprecated-data-object-declaration": "off",
  "vue/no-deprecated-destroyed-lifecycle": "off",
  "vue/no-deprecated-dollar-listeners-api": "off",
  "vue/no-deprecated-dollar-scopedslots-api": "off",
  "vue/no-deprecated-events-api": "off",
  "vue/no-deprecated-filter": "off",
  "vue/no-deprecated-functional-template": "off",
  "vue/no-deprecated-html-element-is": "off",
  "vue/no-deprecated-inline-template": "off",
  "vue/no-deprecated-props-default-this": "off",
  "vue/no-deprecated-router-link-tag-prop": "off",
  "vue/no-deprecated-scope-attribute": "off",
  "vue/no-deprecated-slot-attribute": "off",
  "vue/no-deprecated-slot-scope-attribute": "off",
};
