// 文件自动生成,请勿修改
module.exports = {
  "attribute-hyphenation": "自定义组件属性名必须使用连字符命名",
  "comment-directive": "支持在`<template>`中使用注释指令",
  "component-definition-name-casing": "组件定义名称必须是驼峰式命名",
  "first-attribute-linebreak": "属性的位置必须一致",
  "html-closing-bracket-newline": "标签闭合括号前必须换行",
  "html-closing-bracket-spacing": "标签闭合括号前必须有空格",
  "html-end-tags": "必须使用闭合标签",
  "html-indent": "模板中的缩进必须是2个空格",
  "jsx-uses-vars": "防止在JSX中使用的变量被标记为未使用",
  "multi-word-component-names": "组件名必须是多个单词",
  "no-arrow-functions-in-watch": "禁止在定义观察者时使用箭头函数",
  "no-async-in-computed-properties": "禁止在计算属性中使用异步操作",
  "no-child-content": "禁止元素的子内容被`v-html`或`v-text`指令覆盖",
  "no-computed-properties-in-data": "禁止在`data`中访问计算属性",
  "no-deprecated-data-object-declaration": "禁止在data中使用已废弃的对象声明",
  "no-deprecated-destroyed-lifecycle":
    "禁止使用已废弃的`destroyed`和`beforeDestroy`生命周期钩子(Vue.js 3.0.0+)",
  "no-deprecated-dollar-listeners-api": "禁止使用已废弃的`$listeners`",
  "no-deprecated-dollar-scopedslots-api":
    "禁止使用已废弃的`$scopedSlots` (在Vue.js 3.0.0+中)",
  "no-deprecated-events-api": "禁止使用已废弃的事件API",
  "no-deprecated-filter": "禁止使用已废弃的`functional`模板",
  "no-deprecated-functional-template": "为什么?",
  "no-deprecated-html-element-is": "禁止在HTML元素上使用已废弃的`is`属性",
  "no-deprecated-inline-template": "禁止使用已废弃的`inline-template`属性",
  "no-deprecated-props-default-this": "禁止在props默认函数中使用已弃用的`this`",
  "no-deprecated-router-link-tag-prop":
    "禁止在`RouterLink`上使用已弃用的`tag`属性",
  "no-deprecated-scope-attribute": "禁止使用已废弃的`slot`属性",
  "no-deprecated-slot-attribute": "为什么?",
  "no-deprecated-slot-scope-attribute": "禁止使用已废弃的`slot-scope`属性",
  "no-deprecated-v-bind-sync":
    "禁止在 `v-bind` 指令上使用已废弃的 `.sync` 修饰符 (在 Vue.js 3.0.0+)",
  "no-deprecated-v-is": "禁止使用已废弃的`v-is`指令",
  "no-deprecated-v-on-native-modifier": "禁止使用已废弃的`.native`修饰符",
  "no-deprecated-v-on-number-modifiers": "禁止使用已废弃的数字（键码）修饰符",
  "no-deprecated-vue-config-keycodes": "禁止使用已废弃的`Vue.config.keyCodes`",
  "no-dupe-keys": "禁止字段名重复",
  "no-dupe-v-else-if": "禁止在`v-if` / `v-else-if`链中出现重复的条件",
  "no-duplicate-attributes": "禁止属性重复",
  "no-export-in-script-setup": "禁止在`<script setup>`中使用`export`",
  "no-expose-after-await": "禁止在await表达式后异步注册`expose`",
  "no-lifecycle-after-await": "禁止异步注册生命周期钩子",
  "no-mutating-props": "禁止修改组件的props",
  "no-parsing-error": "禁止在`<template>`中出现解析错误",
  "no-ref-as-operand": "禁止将`ref()`包装的值用作操作数",
  "no-reserved-component-names": "禁止在组件定义中使用保留名称",
  "no-reserved-keys": "禁止覆盖保留关键字",
  "no-reserved-props": "禁止在props中使用保留名称",
  "no-setup-props-destructure": "禁止在`setup`中解构`props`导致失去响应性",
  "no-shared-component-data": "组件的data属性必须是一个函数",
  "no-side-effects-in-computed-properties": "禁止在计算属性中产生副作用",
  "no-template-key": "禁止在`<template>`上使用`key`属性",
  "no-textarea-mustache": "禁止在`<textarea>`中使用插值表达式",
  "no-unused-components": "禁止注册模板中未使用的组件",
  "no-unused-vars": "禁止未使用的v-for指令或作用域属性的变量定义",
  "no-use-computed-property-like-method": "禁止将计算属性用作方法",
  "no-use-v-if-with-v-for": "禁止在同一个元素上同时使用`v-if`和`v-for`",
  "no-useless-template-attributes": "禁止在`<template>`上使用无用的属性",
  "no-v-for-template-key-on-child":
    "禁止在子元素上放置`<template v-for>`的key值",
  "no-v-text-v-html-on-component": "禁止在组件上使用v-text/v-html",
  "no-watch-after-await": "禁止异步注册`watch`",
  "prefer-import-from-vue": "必须从'vue'导入,而不是从'@vue/\\*'导入",
  "require-component-is": "必须在`<component>`元素中使用`v-bind:is`",
  "require-prop-type-constructor": "必须使用构造函数作为prop的类型",
  "require-render-return": "必须在render函数中返回值",
  "require-slots-as-functions": "必须将`$slots`的属性作为函数使用",
  "require-toggle-inside-transition": "必须在`<transition>`内部控制内容的显示",
  "require-v-for-key": "必须在`v-for`指令中使用`v-bind:key`",
  "require-valid-default-prop": "默认属性值必须有效",
  "return-in-computed-property": "计算属性必须有返回值",
  "return-in-emits-validator": "必须在emits验证器中使用return语句",
  "use-v-on-exact": "必须在v-on上使用exact修饰符",
  "valid-attribute-name": "必须使用有效的属性名",
  "valid-define-emits": "强制有效的 `defineEmits` 编译宏",
  "valid-define-props": "强制执行有效的 `defineProps` 编译器宏",
  "valid-next-tick": "必须正确使用`nextTick`函数",
  "valid-template-root": "模板根元素必须有效",
  "valid-v-bind": "必须使用有效的`v-bind`指令",
  "valid-v-cloak": "必须使用有效的`v-cloak`指令",
  "valid-v-else-if": "必须将`else-if`放在`if`后面",
  "valid-v-else": "必须将`v-else`放在最后",
  "valid-v-for": "`v-for`指令必须有效",
  "valid-v-html": "`v-html`指令必须有效",
  "valid-v-if": "`v-if`指令必须有效",
  "valid-v-is": "`v-is`指令必须有效",
  "valid-v-memo": "必须使用有效的`v-memo`指令",
  "valid-v-model": "必须使用有效的`v-model`指令",
  "valid-v-on": "必须使用有效的`v-on`指令",
  "valid-v-once": "必须使用有效的`v-once`指令",
  "valid-v-pre": "必须使用有效的`v-pre`指令",
  "valid-v-show": "`v-show`指令必须有效",
  "valid-v-slot": "`v-slot`指令必须有效",
  "valid-v-text": "强制使用有效的`v-text`指令",
};
