// 文件自动生成,请勿修改
module.exports = {
  "alt-text": "必须为需要替代文本的元素提供描述信息",
  "anchor-has-content": "锚点必须有内容",
  "anchor-is-valid": "禁止使用无效的锚点",
  "aria-activedescendant-has-tabindex":
    "必须为带有aria-activedescendant属性的元素设置tabIndex",
  "aria-props": "元素必须使用有效的ARIA属性",
  "aria-proptypes": "ARIA属性值必须有效",
  "aria-role": "必须使用有效的非抽象ARIA角色",
  "aria-unsupported-elements": "禁止在不支持ARIA的DOM元素上使用ARIA属性",
  "click-events-have-key-events": "必须为onClick事件添加键盘事件",
  "control-has-associated-label": "交互元素必须有文本标签",
  "heading-has-content": "标题元素必须有内容",
  "html-has-lang": "HTML元素必须有lang属性",
  "iframe-has-title": "iframe必须有标题",
  "img-redundant-alt": "图片的alt属性不能包含'image', 'picture', 'photo'等词汇",
  "interactive-supports-focus": "交互元素必须可聚焦",
  "label-has-associated-control": "label必须有文本标签和关联的控件",
  lang: "HTML元素的语言属性必须符合规范",
  "media-has-caption": "媒体必须有字幕",
  "mouse-events-have-key-events": "鼠标事件必须伴随键盘事件",
  "no-access-key": "禁止在元素上使用accessKey属性",
  "no-autofocus": "禁止在元素上使用autoFocus属性",
};
