// 文件内容由代码自动生成,请勿修改
module.exports = {
  "@awawa/array-callback-return": ["error", { allowImplicit: true }],
  "@awawa/block-scoped-var": "error",
  "@awawa/class-methods-use-this": ["error", { exceptMethods: [] }],
  "@awawa/consistent-return": "error",
  "@awawa/curly": ["error", "all"],
  "@awawa/default-case-last": "error",
  "@awawa/default-case": ["error", { commentPattern: "^no default$" }],
  "@awawa/default-param-last": "error",
  "@awawa/dot-location": ["error", "property"],
  "@awawa/dot-notation": ["error", { allowKeywords: true }],
  "@awawa/eqeqeq": ["error", "always", { null: "ignore" }],
  "@awawa/for-direction": "error",
  "@awawa/getter-return": ["error", { allowImplicit: true }],
  "@awawa/grouped-accessor-pairs": ["error", "getBeforeSet"],
  "@awawa/guard-for-in": "error",
  "@awawa/max-classes-per-file": ["error", 1],
  "@awawa/no-alert": "warn",
  "@awawa/no-async-promise-executor": "error",
  "@awawa/no-await-in-loop": "error",
  "@awawa/no-caller": "error",
  "@awawa/no-case-declarations": "error",
  "@awawa/no-compare-neg-zero": "error",
  "@awawa/no-cond-assign": ["error", "always"],
  "@awawa/no-constant-condition": "warn",
  "@awawa/no-constructor-return": "error",
  "@awawa/no-else-return": ["error", { allowElseIf: false }],
  "@awawa/no-empty-function": [
    "error",
    { allow: ["arrowFunctions", "functions", "methods"] },
  ],
  "@awawa/no-empty-pattern": "error",
  "@awawa/no-eval": "error",
  "@awawa/no-extend-native": "error",
  "@awawa/no-extra-bind": "error",
  "@awawa/no-extra-label": "error",
  "@awawa/no-fallthrough": "error",
  "@awawa/no-floating-decimal": "error",
  "@awawa/no-global-assign": ["error", { exceptions: [] }],
  "@awawa/no-implied-eval": "error",
  "@awawa/no-iterator": "error",
  "@awawa/no-labels": ["error", { allowLoop: false, allowSwitch: false }],
  "@awawa/no-lone-blocks": "error",
  "@awawa/no-loop-func": "error",
  "@awawa/no-multi-spaces": ["error", { ignoreEOLComments: false }],
  "@awawa/no-multi-str": "error",
  "@awawa/no-new-func": "error",
  "@awawa/no-new-wrappers": "error",
  "@awawa/no-new": "error",
  "@awawa/no-nonoctal-decimal-escape": "error",
  "@awawa/no-octal-escape": "error",
  "@awawa/no-octal": "error",
  "@awawa/no-param-reassign": [
    "error",
    {
      props: true,
      ignorePropertyModificationsFor: [
        "acc",
        "accumulator",
        "e",
        "ctx",
        "context",
        "req",
        "request",
        "res",
        "response",
        "$scope",
        "staticContext",
      ],
      ignorePropertyModificationsForRegex: ["^effect[A-Z]"],
    },
  ],
  "@awawa/no-proto": "error",
  "@awawa/no-redeclare": "error",
  "@awawa/no-restricted-properties": [
    "error",
    {
      object: "arguments",
      property: "callee",
      message: "arguments.callee is deprecated",
    },
    {
      object: "global",
      property: "isFinite",
      message: "Please use Number.isFinite instead",
    },
    {
      object: "self",
      property: "isFinite",
      message: "Please use Number.isFinite instead",
    },
    {
      object: "window",
      property: "isFinite",
      message: "Please use Number.isFinite instead",
    },
    {
      object: "global",
      property: "isNaN",
      message: "Please use Number.isNaN instead",
    },
    {
      object: "self",
      property: "isNaN",
      message: "Please use Number.isNaN instead",
    },
    {
      object: "window",
      property: "isNaN",
      message: "Please use Number.isNaN instead",
    },
    {
      property: "__defineGetter__",
      message: "Please use Object.defineProperty instead.",
    },
    {
      property: "__defineSetter__",
      message: "Please use Object.defineProperty instead.",
    },
    {
      object: "Math",
      property: "pow",
      message: "Use the exponentiation operator (**) instead.",
    },
  ],
  "@awawa/no-return-assign": ["error", "always"],
  "@awawa/no-script-url": "error",
  "@awawa/no-self-assign": ["error", { props: true }],
  "@awawa/no-self-compare": "error",
  "@awawa/no-sequences": "error",
  "@awawa/no-throw-literal": "error",
  "@awawa/no-unused-expressions": [
    "error",
    {
      allowShortCircuit: true,
      allowTernary: true,
      allowTaggedTemplates: false,
    },
  ],
  "@awawa/no-unused-labels": "error",
  "@awawa/no-useless-catch": "error",
  "@awawa/no-useless-concat": "error",
  "@awawa/no-useless-escape": "error",
  "@awawa/no-useless-return": "error",
  "@awawa/no-void": "error",
  "@awawa/no-with": "error",
  "@awawa/prefer-promise-reject-errors": ["error", { allowEmptyReject: true }],
  "@awawa/prefer-regex-literals": [
    "error",
    { disallowRedundantWrapping: true },
  ],
  "@awawa/radix": "error",
  "@awawa/vars-on-top": "error",
  "@awawa/wrap-iife": ["error", "outside", { functionPrototypeMethods: false }],
  "@awawa/yoda": "error",
};
