// 文件内容由代码自动生成,请勿修改
module.exports = {
  "@awawa/array-callback-return": ["error", { allowImplicit: true }],
  "@awawa/block-scoped-var": "error",
  "@awawa/class-methods-use-this": ["error", { exceptMethods: [] }],
  "@awawa/consistent-return": "error",
  "@awawa/curly": ["error", "all"],
  "@awawa/default-case-last": "error",
  "@awawa/default-case": ["error", { commentPattern: "^no default$" }],
  "@awawa/default-param-last": "error",
  "@awawa/dot-location": ["error", "property"],
  "@awawa/dot-notation": ["error", { allowKeywords: true }],
  "@awawa/eqeqeq": ["error", "always", { null: "ignore" }],
  "@awawa/grouped-accessor-pairs": ["error", "getBeforeSet"],
  "@awawa/guard-for-in": "error",
  "@awawa/max-classes-per-file": ["error", 1],
  "@awawa/no-alert": "warn",
  "@awawa/no-caller": "error",
  "@awawa/no-case-declarations": "error",
  "@awawa/no-constructor-return": "error",
  "@awawa/no-else-return": ["error", { allowElseIf: false }],
  "@awawa/no-empty-function": [
    "error",
    { allow: ["arrowFunctions", "functions", "methods"] },
  ],
  "@awawa/no-empty-pattern": "error",
  "@awawa/no-eval": "error",
  "@awawa/no-extend-native": "error",
  "@awawa/no-extra-bind": "error",
  "@awawa/no-extra-label": "error",
  "@awawa/no-fallthrough": "error",
  "@awawa/no-floating-decimal": "error",
  "@awawa/no-global-assign": ["error", { exceptions: [] }],
  "@awawa/no-implied-eval": "error",
  "@awawa/no-iterator": "error",
  "@awawa/no-labels": ["error", { allowLoop: false, allowSwitch: false }],
  "@awawa/no-lone-blocks": "error",
  "@awawa/no-loop-func": "error",
  "@awawa/no-multi-spaces": ["error", { ignoreEOLComments: false }],
};
