// 文件内容由代码自动生成,请勿修改
module.exports = {
  "react/forbid-prop-types": "off",
  "react/jsx-boolean-value": "off",
  "react/jsx-closing-bracket-location": "off",
  "react/jsx-closing-tag-location": "off",
  "react/jsx-curly-spacing": "off",
  "react/jsx-indent-props": "off",
  "react/jsx-max-props-per-line": "off",
  "react/jsx-no-bind": "off",
  "react/jsx-no-duplicate-props": "off",
  "react/jsx-no-undef": "off",
  "react/jsx-pascal-case": "off",
  "react/jsx-uses-react": "off",
  "react/jsx-uses-vars": "off",
  "react/no-danger": "off",
  "react/no-deprecated": "off",
  "react/no-did-update-set-state": "off",
  "react/no-is-mounted": "off",
  "react/no-string-refs": "off",
  "react/no-unknown-property": "off",
  "react/no-will-update-set-state": "off",
  "react/prefer-es6-class": "off",
  "react/prefer-stateless-function": "off",
};
