// 文件自动生成,请勿修改
module.exports = {
  "forbid-prop-types": "禁止使用any,array,object",
  "jsx-boolean-value": "禁止在JSX中使用布尔值属性",
  "jsx-closing-bracket-location": "必须在JSX多行元素的开头标签位置对齐关闭标签",
  "jsx-closing-tag-location": "多行JSX元素的结束标签位置必须正确",
  "jsx-curly-spacing": "禁止在JSX属性和表达式的花括号内使用空格",
  "jsx-equals-spacing": "JSX属性中的等号两侧必须没有空格",
  "jsx-first-prop-new-line": "必须把第一个属性在新行",
  "jsx-indent-props": "必须使用2个空格缩进JSX中的属性",
  "jsx-indent": "必须使用2个空格进行JSX缩进",
  "jsx-max-props-per-line": "多行属性每行最多只能有一个属性",
  "jsx-no-bind": "禁止在JSX属性中使用.bind()或箭头函数",
  "jsx-no-duplicate-props": "禁止在JSX中使用重复的属性",
  "jsx-no-target-blank":
    '禁止在没有rel="noreferrer"的情况下使用target="\\_blank"属性',
  "jsx-no-undef": "禁止在JSX中使用未声明的组件",
  "jsx-pascal-case": "必须使用驼峰命名自定义组件",
  "jsx-uses-react": "禁止错误地将React标记为未使用",
  "jsx-uses-vars": "禁止未使用的变量",
  "jsx-wrap-multilines": "必须在多行JSX周围添加括号",
  "no-danger": "禁止使用危险的JSX属性",
  "no-deprecated": "禁止使用已废弃的方法",
  "no-did-update-set-state": "禁止在componentDidUpdate中使用setState",
  "no-is-mounted": "禁止使用isMounted",
  "no-string-refs": "禁止使用字符串引用",
  "no-unknown-property": "禁止使用未知的DOM属性",
  "no-will-update-set-state": "禁止在componentWillUpdate中使用setState",
  "prefer-es6-class": "推荐使用ES6类来创建React组件",
  "prefer-stateless-function": "推荐使用纯函数组件",
  "prop-types": "禁止出现未定义过类型的属性",
  "react-in-jsx-scope": "必须引入React",
  "require-render-return": "必须在render函数中返回值",
  "self-closing-comp": "必须使用自闭合标签",
  "sort-comp": "强制组件方法顺序",
};
